apiVersion: v1
kind: Service
metadata:
  name: wayabank-home-website
  labels:
    app: wayabank-home-website
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: wayabank-home-website
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wayabank-home-website
  labels:
    app: wayabank-home-website
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wayabank-home-website
  template:
    metadata:
      labels:
        app: wayabank-home-website
    spec:
      containers:
        - name: wayabank-home-website
          image: 863852973330.dkr.ecr.eu-west-2.amazonaws.com/wayabank-home-website:imgtag
          env:
            - name: MESSAGING_GROUP_ID
              value: "events"
          ports:
            - name: http
              containerPort: 80
      imagePullSecrets:
        - name: dynamowit
